const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const SHORT=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const WEEKS=[
{name:"Week A \u00b7 fast pans",days:[
{title:"Beef skillet",time:"25-35 min",pull:"1.5 lb beef, peppers, onion, cabbage or green beans, salsa",steps:"Brown beef. Add veg 5-7 min. Salsa 2 min.",swap:"Chicken if no beef."},
{title:"Chicken sheet pan",time:"35-40 min 425F",pull:"2-2.5 lb chicken, broccoli, carrots, onion, Mom potato on one end",steps:"Roast 22-28 min to 165F.",swap:"Thighs stay juicier."},
{title:"Pork + vinegar slaw",time:"35 min 400F",pull:"1.5-2 lb pork, cabbage, green beans, vinegar, mustard",steps:"Pork to 145F. Slaw is cabbage+vinegar+mustard. No mayo.",swap:"Sunday chicken if no pork."},
{title:"Baked catfish",time:"25 min 400F",pull:"1.5-2 lb catfish, lemon, paprika, salad",steps:"Bake 12-16 min until it flakes. Do not bread or fry.",swap:"Tilapia backup."},
{title:"Beef pepper skillet",time:"20 min",pull:"Rest of beef, peppers, onion, broccoli, salsa",steps:"Beef+peppers 5 min. Broccoli+salsa lid 5 min.",swap:"Spinach at the end."},
{title:"Chicken fajita bowls",time:"25 min",pull:"Cooked chicken, peppers, onion, salsa, yogurt",steps:"Peppers 6 min. Chicken+salsa 4 min. No tortillas for the men.",swap:"One small corn tortilla for Mom only."},
{title:"Leftover skillet",time:"15-20 min",pull:"Leftovers, salad, salsa, extra eggs if thin",steps:"Veg first, meat in, eggs if needed.",swap:"Empty fridge: 8 eggs + frozen broccoli + salsa."}
]},
{name:"Week B \u00b7 pan sauces",days:[
{title:"Stuffed peppers, beef",time:"45 min 400F",pull:"1.5 lb beef, 3-4 peppers, onion, tomato, cumin. Rice only in Mom halves",steps:"Brown beef. Fill peppers. Bake 25 min.",swap:"Cabbage rolls if no peppers."},
{title:"Mustard-herb chicken + cabbage steaks",time:"40 min 425F",pull:"2 lb thighs, mustard, garlic, cabbage steaks, carrots",steps:"Roast together 25-30 min to 165F. Spoon juices.",swap:"Salsa instead of mustard."},
{title:"Pork medallions, cider pan sauce",time:"40 min",pull:"Pork tenderloin medallions, cider or thinned applesauce, mustard, green beans",steps:"Sear 3 min/side. Deglaze. Return to 145F.",swap:"Lemon+broth if no cider."},
{title:"Catfish with tomato-cucumber relish",time:"30 min",pull:"Catfish, tomato, cucumber, onion, vinegar, lemon, green beans",steps:"Bake fish 12-16 min. Relish on top. No breading.",swap:"Salsa if you do not want to chop."},
{title:"Beef and cabbage skillet",time:"30 min",pull:"1.5 lb beef, cabbage, onion, tomato, paprika",steps:"Brown beef. Cabbage 8 min. Tomato 5 min.",swap:"Add leftover peppers."},
{title:"Chicken chili-verde bowls",time:"35 min",pull:"2 lb chicken, salsa verde or salsa+lime, peppers, yogurt",steps:"Sear chicken. Veg. Simmer salsa 10 min to 165F. Rice on Mom only.",swap:"Pork cubes instead."},
{title:"Hash of leftovers + eggs",time:"20 min",pull:"Leftover meat and veg, 4-6 eggs, salsa",steps:"Crisp veg. Meat. Eggs in wells, lid 4 min.",swap:"Fresh beef + broccoli + eggs."}
]},
{name:"Week C \u00b7 oven + skillet",days:[
{title:"Garlic-tomato beef bake",time:"40 min 400F",pull:"1.5 lb beef, tomato, onion, garlic, zucchini or cabbage",steps:"Brown beef. Bake 20 min with veg buried in sauce.",swap:"Skillet lid instead of oven."},
{title:"Lemon-garlic sheet chicken",time:"40 min 425F",pull:"2 lb chicken, lemon, garlic, broccoli, carrots, Mom potato",steps:"Roast 25 min to 165F. Spoon juices.",swap:"Pork chops pull at 145F."},
{title:"Smothered pork, vinegar onions",time:"40 min",pull:"Pork chops, 2 onions, vinegar, mustard, green beans",steps:"Sear chops. Onions 8 min. Sauce. Lid to 145F.",swap:"Chicken thighs to 165F."},
{title:"Catfish parcels",time:"30 min 400F",pull:"Catfish, peppers, onion, lemon, foil",steps:"Seal in foil. Bake 16-18 min. Salad on the side.",swap:"Tilapia works."},
{title:"Beef fajita skillet",time:"30 min",pull:"Sliced beef or leftover, 3 peppers, 2 onions, salsa, yogurt",steps:"Onions and peppers 8 min. Beef 4 min. No tortillas for men.",swap:"Ground beef if no steak."},
{title:"Yogurt-spice roast chicken",time:"45 min 400F",pull:"2 lb chicken, 1/2 cup yogurt, garlic, paprika, slaw",steps:"Coat. Roast 30-35 min to 165F.",swap:"Works on pork tenderloin at 145F."},
{title:"Kitchen-sink skillet",time:"25 min",pull:"Leftovers, tomato, splash of water, eggs optional",steps:"Simmer 10 min thick, not soup.",swap:"Lid off if watery."}
]}
];
const HOME_PIN="https://www.google.com/maps/dir/?api=1&origin=106+E+Sunset+Dr,+Brandon,+MS+39042&travelmode=walking";
const HOME_TO_PARK="https://www.google.com/maps/dir/106+E+Sunset+Dr,+Brandon,+MS+39042/1451+W+Government+St,+Brandon,+MS+39042/@32.27,-89.99,14z/data=!3e2";
const WALKS={0:["Start at 106 E Sunset \u2014 easy 20-30 min, then home",HOME_PIN],1:["Start at 106 E Sunset \u2014 25-30 min toward College / Government, home",HOME_PIN],2:["Start at 106 E Sunset \u2014 30-35 min, extra block, home",HOME_PIN],3:["Start at 106 E Sunset \u2014 30-40 min loop, home",HOME_PIN],4:["Start at 106 E Sunset \u2014 35-40 min, optional toward City Park, home",HOME_TO_PARK],5:["Start at 106 E Sunset \u2014 30-40 min, home",HOME_PIN],6:["Start at 106 E Sunset \u2014 40-50 min longest. Mom can turn back.",HOME_PIN]};
const GROCERY=["5-6 lb chicken","3.5 lb 93% ground beef","2.5 lb pork","2.5 lb MS catfish","2 dozen eggs","3 tubs plain Greek yogurt","Whey if low","2 bags spinach","2 salad mixes","Cabbage","3 lb green beans","3 bags frozen broccoli","2 bags baby carrots","4 peppers","3 onions","3 cucumbers","Tomatoes or canned tomatoes","Potatoes and/or rice","Cauliflower rice","Garlic, salsa, mustard, hot sauce, oil"];
function names(){try{return JSON.parse(localStorage.getItem("tramel-names"))||{dad:"Thomas",mom:"Mom",son:"Son"};}catch(e){return{dad:"Thomas",mom:"Mom",son:"Son"};}}
function saveNames(n){localStorage.setItem("tramel-names",JSON.stringify(n));}
function shopKey(){const d=new Date();const sun=new Date(d);sun.setDate(d.getDate()-d.getDay());return"shop-"+sun.toISOString().slice(0,10);}
function shopState(){try{return JSON.parse(localStorage.getItem(shopKey()))||{};}catch(e){return{};}}
function toggleShop(i){const s=shopState();s[i]=!s[i];localStorage.setItem(shopKey(),JSON.stringify(s));renderShop();}
function isoWeek(d){const t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const dayNum=t.getUTCDay()||7;t.setUTCDate(t.getUTCDate()+4-dayNum);const yearStart=new Date(Date.UTC(t.getUTCFullYear(),0,1));return Math.ceil((((t-yearStart)/86400000)+1)/7);}
function weekLock(){return localStorage.getItem("tramel-week")||"auto";}
function setWeekLock(v){localStorage.setItem("tramel-week",v);renderToday();renderMeals();}
function activeWeekIndex(){const lock=weekLock();if(lock!=="auto")return Number(lock);return isoWeek(new Date())%WEEKS.length;}
function customRecipes(){try{return JSON.parse(localStorage.getItem("tramel-custom")||"[]");}catch(e){return[];}}
function saveCustom(list){localStorage.setItem("tramel-custom",JSON.stringify(list));}
function pins(){try{return JSON.parse(localStorage.getItem("tramel-pins")||"{}");}catch(e){return{};}}
function savePins(p){localStorage.setItem("tramel-pins",JSON.stringify(p));}
function recipeFor(day){const p=pins()[String(day)];if(p){const c=customRecipes().find(x=>x.id===p);if(c)return{title:c.title,time:c.time||"30-40 min",pull:c.pull,steps:c.steps,swap:c.swap||"Keep ounces.",custom:true};}return WEEKS[activeWeekIndex()].days[day];}
function fitCheck(text){const t=(text||"").toLowerCase();const bad=[];if(/(fried|deep.?fry|breaded|breading|batter)/.test(t))bad.push("No frying or breading.");if(/(flour tortilla|burger bun|pasta for everyone|rice for everyone)/.test(t))bad.push("Starch is Mom's plate only.");const ok=[];if(/(chicken|beef|pork|catfish|tilapia|fish|egg)/.test(t))ok.push("Protein is on-plan.");if(/(pepper|cabbage|broccoli|green bean|onion|spinach|carrot|salad|tomato)/.test(t))ok.push("Vegetables are on-plan.");return{bad,ok};}
function eventsFor(day){const n=names();const walk=WALKS[day];const meal=recipeFor(day);const list=[{t:"5:00",title:"Up, men weigh, family walk",detail:walk[0],who:"all",tag:"Family",map:walk[1]},{t:"5:50",title:"Breakfast",detail:n.dad+" & "+n.son+": 3 eggs + yogurt or whey. "+n.mom+": 2 eggs + yogurt/fruit.",who:"all",tag:"Family"},{t:"4:30",title:"Cook dinner",detail:meal.title+" \u2014 "+meal.pull,who:"all",tag:"Family"},{t:"6:15",title:"Eat together",detail:"Men 8 oz protein. "+n.mom+" 4-5 oz and she gets the starch.",who:"all",tag:"Family"},{t:"8:30",title:"Wind down",detail:"Kitchen closed except protein if short. Lights out 9:00.",who:"all",tag:"Family"}];if(day===1||day===3||day===5)list.splice(3,0,{t:"5:30",title:"Lift 45 min",detail:n.dad+" and "+n.son+". "+n.mom+" optional.",who:"men",tag:"Men"});if(day===0)list.splice(2,0,{t:"8:00",title:"Grocery + prep",detail:"Kroger / Allen's / Cockrell's. Bake chicken, brown beef, boil eggs, chop veg.",who:"all",tag:"Family"});return list;}
function renderToday(){const n=names();document.getElementById("pillDad").textContent=n.dad;document.getElementById("pillMom").textContent=n.mom;document.getElementById("pillSon").textContent=n.son;const now=new Date();const day=now.getDay();const meal=recipeFor(day);const walk=WALKS[day];const ev=eventsFor(day).map(e=>`<div class="event"><time>${e.t}</time><div><b>${e.title}</b><small>${e.detail}${e.map?` \u00b7 <a href="${e.map}" style="color:#d4a017">map</a>`:""}</small></div><span class="who ${e.who}">${e.tag}</span></div>`).join("");document.getElementById("view-today").innerHTML=`<div class="card now"><h2>${DAYS[day]} \u00b7 ${now.toLocaleDateString(undefined,{month:"short",day:"numeric"})}</h2><p>Walk: <a href="${walk[1]}" style="color:#d4a017">${walk[0]}</a></p><p style="margin-top:6px">Dinner: <b>${meal.title}</b> \u2014 ${meal.pull}</p><p class="note">${WEEKS[activeWeekIndex()].name}${meal.custom?" \u00b7 your recipe pinned":""}</p><p style="margin-top:8px;color:#9bb5a6;font-size:.82rem">Heat index over 95F, ice, lightning, or hard rain \u2192 treadmill 3.0-3.3 mph, 1-2% incline.</p></div><div class="card"><h2>Today's clock</h2>${ev}</div><div class="card"><h2>Three plates</h2><div class="plate"><div><h3 style="color:#5b9fd4">${n.dad}</h3>8 oz meat \u00b7 2 cups veg \u00b7 starch only if hungry \u00b7 2,000-2,300 kcal</div><div><h3 style="color:#7d6ad9">${n.son}</h3>Same cut as Dad. Lift together. Doctor visit still needed.</div><div><h3 style="color:#d46b8a">${n.mom}</h3>4-5 oz meat \u00b7 2 cups veg \u00b7 she eats the potato/rice/fruit. No deficit.</div></div></div>`;}
function renderWeek(){const now=new Date();const selected=Number(document.getElementById("view-week").dataset.day??now.getDay());const buttons=SHORT.map((s,i)=>`<button class="daybtn ${i===selected?"on":""}" onclick="pickDay(${i})">${s}</button>`).join("");const ev=eventsFor(selected).map(e=>`<div class="event"><time>${e.t}</time><div><b>${e.title}</b><small>${e.detail}</small></div><span class="who ${e.who}">${e.tag}</span></div>`).join("");document.getElementById("view-week").innerHTML=`<div class="card"><h2>Pick a day</h2><div class="week">${buttons}</div></div><div class="card"><h2>${DAYS[selected]}</h2>${ev}</div>`;}
function pickDay(i){document.getElementById("view-week").dataset.day=i;renderWeek();}
function renderMeals(){const wi=activeWeekIndex();const lock=weekLock();const mine=customRecipes();const cards=DAYS.map((d,i)=>{const r=recipeFor(i);return `<div class="card"><h2>${SHORT[i]} \u00b7 ${r.title}${r.custom?" \u2605":""}</h2><p style="color:var(--gold);font-size:.8rem;margin-bottom:8px">${r.time} \u00b7 start 4:30</p><p style="font-size:.85rem"><b>Pull</b> ${r.pull}</p><p style="font-size:.85rem;margin-top:6px"><b>Cook</b> ${r.steps}</p><p style="font-size:.85rem;margin-top:6px"><b>Plate</b> Men 8 oz \u00b7 Mom 4-5 oz \u00b7 she gets the starch</p><p class="note" style="margin-top:6px"><b>Swap</b> ${r.swap}</p></div>`;}).join("");const customCards=mine.length?mine.map(c=>{const fit=fitCheck(c.title+" "+c.pull+" "+c.steps);return `<div class="card"><h2>${c.title}</h2><p class="note">${c.time||""} \u00b7 ${c.pull||""}</p><p style="font-size:.85rem;margin-top:6px">${c.steps||""}</p>${fit.ok.map(x=>`<p class="ok">${x}</p>`).join("")}${fit.bad.map(x=>`<p class="bad">${x}</p>`).join("")}<p class="note" style="margin-top:8px">Pin to a night:</p>${SHORT.map((s,i)=>`<button class="ghost" onclick="pinRecipe('${c.id}',${i})">${s}</button>`).join(" ")}<button class="ghost" onclick="deleteRecipe('${c.id}')">Delete</button></div>`;}).join(""):`<p class="note">None saved yet.</p>`;document.getElementById("view-meals").innerHTML=`<div class="card now"><h2>This week's rotation</h2><p style="font-size:.85rem">${WEEKS[wi].name}. Auto flips every Sunday.</p><p style="margin-top:8px"><button class="${lock==="auto"?"btn":"ghost"}" onclick="setWeekLock('auto')">Auto</button>${WEEKS.map((w,i)=>`<button class="${lock===String(i)?"btn":"ghost"}" onclick="setWeekLock('${i}')">${w.name.split("\u00b7")[0]}</button>`).join("")}</p></div><div class="card now"><h2>Breakfast 5:50</h2><p style="font-size:.85rem">Men: 3 eggs or 2 eggs + whey + yogurt. Mom: 2 eggs + yogurt or fruit.</p></div>${cards}<div class="card"><h2>Your recipes</h2>${customCards}</div><div class="card"><h2>Add a family recipe</h2><input type="text" id="crTitle" placeholder="Name" /><input type="text" id="crTime" placeholder="35 min" /><input type="text" id="crPull" placeholder="What to pull" /><textarea id="crSteps" rows="4" placeholder="How to cook. Rice on Mom only."></textarea><input type="text" id="crSwap" placeholder="Swap" /><p id="crFit"></p><button class="btn" onclick="previewFit()">Check if it fits</button><button class="btn" onclick="addRecipe()">Save to this phone</button></div><div class="card maps"><h2>Walks start at the house</h2><a href="${HOME_PIN}"><strong>106 E Sunset Dr</strong><br>Walking directions from the driveway</a><a href="${HOME_TO_PARK}"><strong>Optional Thursday</strong><br>Toward City Park, then home</a></div>`;}
function renderShop(){const st=shopState();const items=GROCERY.map((g,i)=>`<label class="check ${st[i]?"done":""}"><input type="checkbox" ${st[i]?"checked":""} onchange="toggleShop(${i})" /><span>${g}</span></label>`).join("");document.getElementById("view-shop").innerHTML=`<div class="card"><h2>Sunday cart</h2>${items}<p class="note" style="margin-top:8px">Kroger 1811 W Government or 1070 Spillway Cir \u00b7 Allen's 766 Hwy 468 \u00b7 Cockrell's 1307 Old Fannin Rd</p></div>`;}
function renderShare(){const n=names();document.getElementById("view-share").innerHTML=`<div class="card"><h2>Names</h2><input id="nDad" value="${n.dad}" /><input id="nMom" value="${n.mom}" /><input id="nSon" value="${n.son}" /><button class="btn" onclick="applyNames()">Save names</button></div><div class="card"><h2>Live site</h2><p class="note">Add this URL to Home Screen from Safari. After Grok updates, pull down to refresh.</p><p><a href="https://thomastramel2011-debug.github.io/tramel-family-calendar/" style="color:#d4a017">thomastramel2011-debug.github.io/tramel-family-calendar</a></p></div><div class="card"><h2>iPhone apps</h2><a class="btn" href="https://apps.apple.com/us/app/map-my-walk-walking-tracker/id307861492">Map My Walk</a><a class="btn" href="https://apps.apple.com/us/app/google-maps/id585978410">Google Maps</a><a class="btn" href="https://apps.apple.com/us/app/hevy-gym-log-workout-tracker/id1453402470">Hevy</a><a class="btn" href="https://apps.apple.com/us/app/myfitnesspal-calorie-counter/id341232718">MyFitnessPal</a></div>`;}
function previewFit(){const text=[document.getElementById("crTitle").value,document.getElementById("crPull").value,document.getElementById("crSteps").value].join(" ");const fit=fitCheck(text);document.getElementById("crFit").innerHTML=fit.ok.map(x=>`<span class="ok">${x}</span>`).join(" ")+" "+(fit.bad.length?fit.bad.map(x=>`<span class="bad">${x}</span>`).join(" "):`<span class="ok">On-plan if men 8 oz, Mom 4-5 oz.</span>`);}
function addRecipe(){const title=document.getElementById("crTitle").value.trim();if(!title){alert("Give it a name.");return;}const list=customRecipes();list.push({id:"r"+Date.now(),title,time:document.getElementById("crTime").value.trim()||"30-40 min",pull:document.getElementById("crPull").value.trim(),steps:document.getElementById("crSteps").value.trim(),swap:document.getElementById("crSwap").value.trim()});saveCustom(list);renderMeals();}
function pinRecipe(id,day){const p=pins();p[String(day)]=id;savePins(p);renderToday();renderMeals();}
function deleteRecipe(id){saveCustom(customRecipes().filter(x=>x.id!==id));const p=pins();Object.keys(p).forEach(k=>{if(p[k]===id)delete p[k];});savePins(p);renderMeals();}
function applyNames(){saveNames({dad:document.getElementById("nDad").value.trim()||"Thomas",mom:document.getElementById("nMom").value.trim()||"Mom",son:document.getElementById("nSon").value.trim()||"Son"});renderToday();}
const views=["today","week","meals","shop","share"];document.querySelectorAll("nav button").forEach(btn=>{btn.onclick=()=>{document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active"));btn.classList.add("active");views.forEach(v=>{document.getElementById("view-"+v).hidden=v!==btn.dataset.view;});if(btn.dataset.view==="today")renderToday();if(btn.dataset.view==="week")renderWeek();if(btn.dataset.view==="meals")renderMeals();if(btn.dataset.view==="shop")renderShop();if(btn.dataset.view==="share")renderShare();};});
renderToday();
